### ISSUE TITLE
ipfs-repo-migrations v8.0.0 giving `Cannot find name 'getVersion'.` while using typescript

### ISSUE THREAD

**Issue by manas99** [ipfs/js-ipfs-repo-migrations#120]
Using `ipfs-core` with angular typescript giving error:

```
Error: node_modules/ipfs-repo-migrations/dist/src/index.d.ts:55:10 - error TS2304: Cannot find name 'getVersion'.
55 export { getVersion as getCurrentRepoVersion, errors };
```

### System Details to recreate:
```
OS: macOS 11.0.1
ipfs-core: v0.8.0
angular: v12.1.2
typescript: v4.3.2
ipfs-repo-migrations v8.0.0
```

### Description:
The `getVersion` function is exported in `index.d.ts`, but it is not imported. Hence the not found error.

### Proposed fix:
I am not exactly sure whether it should be done this way as I am testing it...
importing the `getVersion` function with the following line:
`import getVersion = require("./repo/version")`

or to remove the getVersion from `export { getVersion as getCurrentRepoVersion, errors };`

**Comment by BigLep** [comment]
Closing because repo is archived
