### ISSUE TITLE
Migration progress

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-repo-migrations#32]
At the moment there's no progress available during a migration.  These can take a long time so it's a poor user experience.

You should be able to pass a callback that gets invoked with some sort of notion of how much information has been processed and how much is left.

**Comment by AuHau** [comment]
Well, there is the `onProgress` callback, but this only reports on what migration you are currently migrating... Just to think about if the "in-migration-progress" should be part of this callback or it should be a different one.

**Comment by achingbrain** [comment]
Yes, I was thinking something a bit more fine-grained, though obviously it becomes harder to be generic as the migrations are not typically similar.

Something like this would probably work:

```javascript
migrate(..., {
  onProgress: ({ migration: { from, to }, percent, message }) => {}
})
```
