### ISSUE TITLE
Incompatibility with "zii"

### ISSUE THREAD

**Issue by KyleMaas** [ipfs/js-ipfs-repo-migrations#61]
Reported upstream here: https://github.com/multiformats/js-multibase/issues/80

This line, when called within an npm project which also contains "zii" from another package, crashes:

https://github.com/ipfs/js-ipfs-repo-migrations/blob/425d53c5f2ef2d89b11d2cfc33362d5ebfad81a5/migrations/migration-9/utils.js#L10

**Comment by aschmahmann** [comment]
closing since the conversation on this is happening in the multibase repo
