### ISSUE TITLE
Bump js-multibase to 4.0.0

### ISSUE THREAD

**Issue by KyleMaas** [ipfs/js-ipfs-repo-migrations#68]
js-multibase just released version 4.0.0, which fixed an issue that was impacting the ssb-browser-demo project.  Is it possible this could be updated to use the new version please?

**Comment by KyleMaas** [comment]
See https://github.com/multiformats/js-multibase/issues/80 for details as to why this is needed.

**Comment by achingbrain** [comment]
Fixed in #66

**Comment by KyleMaas** [comment]
Excellent.  Thank you!
